### ISSUE TITLE
PyBluez import throws exception

### ISSUE THREAD

**Issue by grant-h** [OSUSecLab/DongleScope#1]
Machine info:

macOS Version: 10.14.6 (Mojave)
Python 2.7.17 (default, Oct 24 2019, 12:57:47)

Install steps:
```
virtualenv -p python2 venv
source venv/bin/activate
pip install -r requirement.txt
```

`pip freeze`:
```
pyble==0.2
PyBluez==0.23
pyobjc-core==5.3
pyobjc-framework-Cocoa==5.3
pyserial==3.4
```

Running
```
$ python main.py
Traceback (most recent call last):
  File "main.py", line 3, in <module>
    from bluetooth import *
  File "/Users/xyz/DongleScope/venv/lib/python2.7/site-packages/bluetooth/__init__.py", line 282, in <module>
    """
AttributeError: attribute '__doc__' of 'instancemethod' objects is not writable
```

Googling this leads to mention that this is a Python2/3 incompatibility. How was this resolved on the authors machine? Downgrading to PyBluez to 0.22 (2015) causes compilation failures. I'm trying to avoid hacking up the virtual env sources.

**Comment by grebtsew** [comment]
Hello,

A couple of years late perhaps, but the issue you experience is due to using a too new version of PyBluez.
Try using: PyBluez==0.20 instead. 

I will also mention that pyble==0.2 is the wrong dependency, instead use: git+https://github.com/brettchien/PyBLEWrapper.git@0.2.6.

I have created a PR as a potential fix to compensate for this. Here : https://github.com/OSUSecLab/DongleScope/pull/2

Cheers,
@Grebtsew
